"""db column names update

Revision ID: f4335debdd12
Revises: 4a58d9f15984
Create Date: 2023-09-08 07:41:43.759298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4335debdd12'
down_revision: Union[str, None] = '4a58d9f15984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('f_name', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('l_name', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('department', sa.String(), nullable=True))
    op.drop_column('candidates', 'course')
    op.drop_column('candidates', 'last_name')
    op.drop_column('candidates', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('first_name', sa.VARCHAR(), nullable=False))
    op.add_column('candidates', sa.Column('last_name', sa.VARCHAR(), nullable=False))
    op.add_column('candidates', sa.Column('course', sa.VARCHAR(), nullable=True))
    op.drop_column('candidates', 'department')
    op.drop_column('candidates', 'l_name')
    op.drop_column('candidates', 'f_name')
    # ### end Alembic commands ###
